# Harmony Jekyll theme general configurations

# Base URL
# baseurl: /

# Site live URL
# url: blog.youdaxue.com

# Localhost
#url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: 高民权（Minchiuan Gao）| 的博客
  # Little description about your site
  description: > #
   高民权的记录
  keywords: >
    机器学习,,编程技术，博客
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Minchiuan's Blog
    email: minchiuan.gao@gmail.com
    url: https://github.com/fortymiles

  # Google Analytics key, leave blank to ignore
  google_analytics_key: 

  # Profile links, leave blank to ignore
  social:
    github: fortymiles
    twitter: udacity
    facebook:
    gplus:
    dribble:
    pinterest:
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
