# Site settings
title: minchuian
email: minchiuan.gao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    There is a better world :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  fortyMiles

# Build settings
markdown: kramdown
kramdown:
    input: GFM


